import { Component } from '@angular/core';
import { BarcodeFormat, BarcodeScanner } from '@capacitor-mlkit/barcode-scanning';
import { ApiService, Family, PantryInputCandidate, PantryItem } from '../services/api.service';

interface PantryForm { name: string; quantity: string; unit: string; purchase_date: string; expiry_date: string; freshness_review_date: string; purchase_source: string; storage_type: string; freshness_condition: string; family_id: number | null; }
@Component({ selector: 'app-pantry', templateUrl: 'pantry.page.html', styleUrls: ['pantry.page.scss'], standalone: false })
export class PantryPage {
  personalItems: PantryItem[] = []; householdItems: PantryItem[] = []; families: Family[] = []; form: PantryForm = this.emptyForm(); editingId: number | null = null;
  message = ''; saving = false; processingInput = false; listening = false; receiptText = '';
  drafts: PantryInputCandidate[] = [];
  showAdvancedDetails = false;
  readonly commonUnits = ['pieces', 'cans', 'packs', 'bottles', 'boxes', 'kg', 'g', 'ml', 'litre'];
  private recognition: any; private voiceTranscript = '';
  constructor(private api: ApiService) {}
  ionViewWillEnter() { this.loadFamilies(); }
  loadPantryItems(familyId: number | null = this.form.family_id) { if (!this.api.hasToken) return; this.api.pantry(undefined, true).subscribe({ next: items => this.personalItems = items, error: () => this.message = 'Your account session has expired. Please sign in again.' }); if (familyId) this.api.pantry(familyId).subscribe({ next: items => this.householdItems = items.filter(item => item.family_id === familyId), error: () => this.message = 'Your account session has expired. Please sign in again.' }); else this.householdItems = []; }
  loadFamilies() { this.api.families().subscribe({ next: families => { this.families = families; const activeId = Number(localStorage.getItem('whattocook_active_family')); this.form.family_id = families.some(family => family.id === activeId) ? activeId : null; this.loadPantryItems(this.form.family_id); }, error: () => this.loadPantryItems(null) }); }
  startAdd() { const familyId = this.form.family_id; this.editingId = null; this.form = this.emptyForm(familyId); this.showAdvancedDetails = false; this.message = ''; }
  adjustQuantity(change: number) { const next = Math.max(1, Number(this.form.quantity || 0) + change); this.form.quantity = String(next); }
  chooseUnit(unit: string) { this.form.unit = unit; }
  suggestUnit() { if (this.form.unit) return; const name = this.form.name.toLowerCase(); if (/\b(egg|eggs)\b/.test(name)) this.form.unit = 'pieces'; else if (/\b(can|tuna|sardines|coconut milk)\b/.test(name)) this.form.unit = 'cans'; }
  edit(item: PantryItem) { this.editingId = item.id; this.form = { name: item.name, quantity: item.quantity || item.quantity_value?.toString() || '', unit: item.unit || '', purchase_date: this.dateOnly(item.purchase_date), expiry_date: this.dateOnly(item.expiry_date), freshness_review_date: this.dateOnly(item.freshness_review_date), purchase_source: item.purchase_source || 'unknown', storage_type: item.storage_type || 'unknown', freshness_condition: item.freshness_condition || 'unknown', family_id: item.family_id ?? null }; window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async scanBarcode() { try { const { supported } = await BarcodeScanner.isSupported(); if (!supported) { this.message = 'Barcode scanning is not supported on this device. Enter the item manually.'; return; } const { barcodes } = await BarcodeScanner.scan({ formats: [BarcodeFormat.Ean13, BarcodeFormat.Ean8, BarcodeFormat.UpcA, BarcodeFormat.UpcE] }); if (barcodes[0]?.displayValue) this.lookupBarcode(barcodes[0].displayValue); } catch { this.message = 'Camera scan was cancelled or permission was not granted.'; } }
  lookupBarcode(barcode: string) { this.processingInput = true; this.api.barcodeInput(barcode).subscribe({ next: result => this.applyCandidates(result.candidates, result.message), error: () => { this.form.name = barcode; this.message = 'Barcode captured. Product lookup failed; enter its name and confirm the details.'; this.processingInput = false; } }); }
  startVoice() { const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!SpeechRecognition) { this.message = 'Voice input is not supported in this browser. Use Chrome on Android or enter the item manually.'; return; } const recognition = this.recognition = new SpeechRecognition(); this.voiceTranscript = ''; recognition.lang = 'en-PH'; recognition.interimResults = false; recognition.continuous = true; recognition.maxAlternatives = 1; this.listening = true; this.message = 'Recording… say one or more items, then tap Stop voice.'; recognition.onresult = (event: any) => { const transcript = Array.from(event.results).map((result: any) => result[0].transcript).join(' ').trim(); if (transcript) this.voiceTranscript = transcript; }; recognition.onerror = (event: any) => { this.listening = false; this.recognition = undefined; this.message = event.error === 'not-allowed' ? 'Microphone permission was denied. Allow it in your browser site settings and try again.' : 'Voice recording could not start. Please try again.'; }; recognition.onend = () => { this.listening = false; if (this.recognition === recognition) this.recognition = undefined; }; recognition.start(); }
  stopVoice() { if (!this.recognition) return; const transcript = this.voiceTranscript; this.recognition.stop(); this.listening = false; if (!transcript) { this.message = 'No speech was captured. Check microphone permission, then try again and speak before stopping.'; return; } this.processingInput = true; this.message = 'Processing speech…'; this.api.voiceInput(transcript).subscribe({ next: result => this.applyCandidates(result.candidates, result.message), error: () => { this.message = 'Speech was captured but could not reach the backend. Make sure Laravel is running, then try again.'; this.processingInput = false; } }); }
  uploadReceipt(event: Event) { const receipt = (event.target as HTMLInputElement).files?.[0]; if (!receipt) return; this.processingInput = true; this.api.receiptInput(receipt, this.receiptText).subscribe({ next: result => this.applyCandidates(result.candidates, result.message), error: error => { this.message = error?.error?.message || 'Could not upload the receipt.'; this.processingInput = false; } }); }
  useDraft(draft: PantryInputCandidate) { this.applyCandidate(draft, 'Review this draft, then add it to the pantry.'); this.drafts = this.drafts.filter(item => item !== draft); }
  private applyCandidates(candidates: PantryInputCandidate[], message: string) { this.drafts = [...candidates]; this.applyCandidate(this.drafts.shift(), candidates.length > 1 ? `${message} Review each detected item below.` : message); }
  private applyCandidate(candidate: PantryInputCandidate | undefined, message: string) { if (candidate) { this.form.name = candidate.name || this.form.name; this.form.quantity = candidate.quantity || this.form.quantity; this.form.unit = candidate.unit || this.form.unit; this.form.purchase_source = candidate.purchase_source || this.form.purchase_source; this.form.storage_type = candidate.storage_type || this.form.storage_type; } this.message = message; this.processingInput = false; }
  savePantryItem() { if (!this.form.name.trim() || !Number(this.form.quantity) || !this.form.unit.trim()) { this.message = 'Enter an ingredient, a positive quantity, and a unit.'; return; } this.saving = true; this.message = ''; const request = this.editingId ? this.api.updatePantry(this.editingId, this.form) : this.api.addPantry(this.form); request.subscribe({ next: () => { const familyId = this.form.family_id; this.editingId = null; this.form = this.emptyForm(familyId); this.message = 'Pantry item saved.'; this.saving = false; this.loadPantryItems(familyId); }, error: error => { this.message = error?.error?.message || 'Could not save the pantry item.'; this.saving = false; } }); }
  deletePantryItem(item: PantryItem) { if (!confirm(`Delete ${item.name} from the pantry?`)) return; this.api.deletePantry(item.id).subscribe({ next: () => { if (this.editingId === item.id) this.startAdd(); this.message = 'Pantry item deleted.'; this.loadPantryItems(); }, error: () => this.message = 'Could not delete the pantry item.' }); }
  recordFreshnessAction(item: PantryItem, action: 'still_fresh' | 'spoiled' | 'used' | 'discarded' | 'undo_used') { let usedQuantity: number | undefined; if (action === 'used') { const answer = prompt(`How much ${item.name} was used? Available: ${item.quantity_value || item.quantity} ${item.unit || ''}`); if (answer === null) return; usedQuantity = Number(answer); if (!usedQuantity || usedQuantity <= 0) { this.message = 'Enter a positive amount used.'; return; } } this.api.updateFreshness(item.id, action, usedQuantity).subscribe({ next: ({ item: updated }) => { this.message = `${updated.name} updated.`; this.loadPantryItems(); }, error: error => this.message = error?.error?.message || 'Could not update freshness.' }); }
  isAttention(item: PantryItem): boolean { return item.freshness_status === 'review' || (!!item.freshness_review_date && new Date(item.freshness_review_date).getTime() <= Date.now()); }
  private emptyForm(familyId: number | null = null): PantryForm { return { name: '', quantity: '1', unit: '', purchase_date: new Date().toISOString().slice(0, 10), expiry_date: '', freshness_review_date: '', purchase_source: 'unknown', storage_type: 'unknown', freshness_condition: 'unknown', family_id: familyId }; }
  private dateOnly(value?: string): string { return value ? value.slice(0, 10) : ''; }
}
