import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { BarcodeFormat, BarcodeScanner } from '@capacitor-mlkit/barcode-scanning';
import { SpeechRecognition } from '@capacitor-community/speech-recognition';
import { TextRecognition } from '@capacitor-mlkit/text-recognition';
import { Camera, CameraResultType, CameraSource } from '@capacitor/camera';
import { Capacitor } from '@capacitor/core';
import { Filesystem } from '@capacitor/filesystem';
import { ApiService, Family, PantryInputCandidate, PantryItem } from '../services/api.service';
import { AuthService } from '../services/auth.service';
import { HouseholdContextService } from '../services/household-context.service';
import { PantryInputCacheService } from '../services/pantry-input-cache.service';
import { ModalController } from '@ionic/angular';
import { UseAmountModalComponent } from './use-amount-modal.component';

interface PantryForm { name: string; quantity: string; unit: string; purchase_date: string; expiry_date: string; freshness_review_date: string; purchase_source: string; storage_type: string; freshness_condition: string; family_id: number | null; }

/** A deliberately conservative client-only receipt parser. Every result remains editable. */
export function receiptCandidates(text: string): PantryInputCandidate[] {
  const ignored = /^(total|subtotal|change|cash|vat|date|receipt|discount|tender|balance)\b/i;
  return text.split(/\r?\n/).map(line => line.trim()).filter(line => line && !ignored.test(line)).map(line => {
    const withoutPrice = line.replace(/\s+(?:₱|php)?\s*[\d,.]+\s*$/i, '').trim();
    const match = withoutPrice.match(/^(\d+(?:\.\d+)?)\s*(?:x|pcs?\.?|pieces?)?\s+(.+)$/i);
    return { name: (match?.[2] || withoutPrice).replace(/\s{2,}/g, ' ').trim(), quantity: match?.[1] || '1', unit: 'pieces', purchase_source: 'unknown', storage_type: 'unknown' };
  }).filter(candidate => candidate.name.length > 1 && /[a-z]/i.test(candidate.name));
}

@Component({ selector: 'app-pantry', templateUrl: 'pantry.page.html', styleUrls: ['pantry.page.scss'], standalone: false })
export class PantryPage {
  personalItems: PantryItem[] = []; householdItems: PantryItem[] = []; families: Family[] = []; activeFamily?: Family; viewFamilyId: number | null = null; form: PantryForm = this.emptyForm(); editingId: number | null = null;
  message = ''; saving = false; processingInput = false; listening = false; receiptText = ''; voiceReviewTranscript = ''; receiptReviewText = '';
  drafts: PantryInputCandidate[] = []; suggestedCandidates: PantryInputCandidate[] = []; rejectedCandidates: PantryInputCandidate[] = []; pendingSuggestion?: PantryInputCandidate; showAdvancedDetails = false; returnToMealId?: number;
  private requestedScope?: 'personal' | 'family'; private requestedFamilyId?: number;
  readonly commonUnits = ['pieces', 'cans', 'packs', 'bottles', 'boxes', 'kg', 'g', 'ml', 'litre'];
  private recognition: any; private voiceTranscript = ''; private stoppingVoice = false; private nativeSpeechListener?: { remove: () => Promise<void> };
  constructor(private api: ApiService, private householdContext: HouseholdContextService, private auth: AuthService, private inputCache: PantryInputCacheService, private route: ActivatedRoute, private router: Router, private modalController: ModalController) {}
  ionViewWillEnter() { this.readMealReturnContext(); this.loadFamilies(); }
  loadPantryItems(familyId: number | null = this.viewFamilyId) { if (!this.api.hasToken) return; this.api.pantry(undefined, true).subscribe({ next: items => this.personalItems = items, error: () => this.message = 'Your account session has expired. Please sign in again.' }); if (familyId) this.api.pantry(familyId).subscribe({ next: items => this.householdItems = items.filter(item => item.family_id === familyId), error: () => this.message = 'Your account session has expired. Please sign in again.' }); else this.householdItems = []; }
  loadFamilies() { const userId = this.auth.user?.id; this.householdContext.refresh(userId).subscribe({ next: context => { this.families = context.families; const requestedFamily = this.requestedScope === 'family' ? this.families.find(family => family.id === this.requestedFamilyId) : undefined; if (requestedFamily && userId) this.householdContext.select(userId, requestedFamily); this.activeFamily = requestedFamily || context.activeFamily || undefined; this.viewFamilyId = this.activeFamily?.id || null; if (!this.editingId && !this.form.name.trim() && this.requestedScope) this.form.family_id = this.requestedScope === 'family' ? this.viewFamilyId : null; if (this.form.family_id !== null && !this.families.some(family => family.id === this.form.family_id)) this.form.family_id = this.viewFamilyId; this.loadPantryItems(); }, error: () => { this.families = []; this.activeFamily = undefined; this.viewFamilyId = null; this.message = 'Could not load your household. Showing your personal pantry only.'; this.loadPantryItems(null); } }); }
  startAdd() { const familyId = this.form.family_id; this.editingId = null; this.form = this.emptyForm(familyId); this.showAdvancedDetails = false; this.message = ''; }
  adjustQuantity(change: number) { this.form.quantity = String(Math.max(1, Number(this.form.quantity || 0) + change)); }
  chooseUnit(unit: string) { this.form.unit = unit; }
  suggestUnit() { if (!this.form.unit) { const name = this.form.name.toLowerCase(); if (/\b(egg|eggs)\b/.test(name)) this.form.unit = 'pieces'; else if (/\b(can|tuna|sardines|coconut milk)\b/.test(name)) this.form.unit = 'cans'; } this.validateManualIngredient(); }
  validateManualIngredient() { const name = this.form.name.trim(); if (!name || this.editingId) return; this.api.resolveIngredient(name).subscribe({ next: candidate => { if (candidate.status === 'suggested') this.pendingSuggestion = candidate; else if (candidate.status === 'rejected') { this.pendingSuggestion = undefined; this.message = candidate.message || 'This is not a recognised food ingredient.'; } else this.pendingSuggestion = undefined; }, error: () => undefined }); }
  confirmSuggestion() { if (!this.pendingSuggestion?.suggestion) return; this.form.name = this.pendingSuggestion.suggestion.canonical_name; if (!this.form.unit && this.pendingSuggestion.suggestion.default_units?.[0]) this.form.unit = this.pendingSuggestion.suggestion.default_units[0]; this.message = `Using ${this.form.name}.`; this.pendingSuggestion = undefined; }
  edit(item: PantryItem) { this.editingId = item.id; this.form = { name: item.name, quantity: item.quantity || item.quantity_value?.toString() || '', unit: item.unit || '', purchase_date: this.dateOnly(item.purchase_date), expiry_date: this.dateOnly(item.expiry_date), freshness_review_date: this.dateOnly(item.freshness_review_date), purchase_source: item.purchase_source || 'unknown', storage_type: item.storage_type || 'unknown', freshness_condition: item.freshness_condition || 'unknown', family_id: item.family_id ?? null }; window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async scanBarcode() { try { const { supported } = await BarcodeScanner.isSupported(); if (!supported) { this.message = 'Barcode scanning is not supported on this device. Enter the item manually.'; return; } const { barcodes } = await BarcodeScanner.scan({ formats: [BarcodeFormat.Ean13, BarcodeFormat.Ean8, BarcodeFormat.UpcA, BarcodeFormat.UpcE] }); if (barcodes[0]?.displayValue) this.lookupBarcode(barcodes[0].displayValue); } catch { this.message = 'Camera scan was cancelled or permission was not granted.'; } }
  lookupBarcode(barcode: string) { const cached = this.inputCache.getBarcode(barcode); if (cached) { this.applyResult(cached); return; } this.processingInput = true; this.api.barcodeInput(barcode).subscribe({ next: result => { this.inputCache.putBarcode(barcode, result); this.applyResult(result); }, error: () => { this.form.name = barcode; this.message = 'Barcode captured. Product lookup failed; enter its name and confirm the details.'; this.processingInput = false; } }); }
  async startVoice() { if (Capacitor.isNativePlatform()) return this.startNativeVoice(); this.startBrowserVoice(); }
  private async startNativeVoice() { try { const available = await SpeechRecognition.available(); if (!available.available) throw new Error('unavailable'); const permission = await SpeechRecognition.requestPermissions(); if (permission.speechRecognition !== 'granted') { this.message = 'Microphone permission was denied. Allow microphone access in Android settings and try again.'; return; } this.voiceTranscript = ''; this.voiceReviewTranscript = ''; this.listening = true; this.message = 'Recording… say one or more items, then tap Stop voice.'; this.nativeSpeechListener = await SpeechRecognition.addListener('partialResults', ({ matches }) => this.voiceTranscript = matches.join(' ').trim()); const result = await SpeechRecognition.start({ language: 'en-PH', maxResults: 1, partialResults: true, popup: false }); if (result.matches?.length) this.voiceTranscript = result.matches.join(' ').trim(); } catch { this.listening = false; this.message = 'Native voice recognition is unavailable. You can enter the item manually.'; } }
  private startBrowserVoice() { const BrowserSpeech = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!BrowserSpeech) { this.message = 'Voice input is not supported in this browser. Enter the item manually.'; return; } const recognition = this.recognition = new BrowserSpeech(); this.voiceTranscript = ''; this.voiceReviewTranscript = ''; this.stoppingVoice = false; recognition.lang = 'en-PH'; recognition.interimResults = false; recognition.continuous = true; recognition.maxAlternatives = 1; this.listening = true; this.message = 'Recording… say one or more items, then tap Stop voice.'; recognition.onresult = (event: any) => { const transcript = Array.from(event.results).map((result: any) => result[0].transcript).join(' ').trim(); if (transcript) this.voiceTranscript = transcript; }; recognition.onerror = () => { this.listening = false; this.recognition = undefined; this.message = 'Voice recording could not start. Please try again.'; }; recognition.onend = () => { this.listening = false; if (this.recognition === recognition) this.recognition = undefined; if (this.stoppingVoice) { this.stoppingVoice = false; this.openVoiceReview(); } }; recognition.start(); }
  async stopVoice() { this.listening = false; this.message = 'Preparing your voice text for review…'; if (Capacitor.isNativePlatform()) { try { await SpeechRecognition.stop(); } finally { await this.nativeSpeechListener?.remove(); this.nativeSpeechListener = undefined; this.openVoiceReview(); } return; } if (!this.recognition) return; this.stoppingVoice = true; this.recognition.stop(); }
  confirmVoiceTranscript() { const transcript = this.voiceReviewTranscript.trim(); if (!transcript) { this.message = 'Enter or speak an item before confirming.'; return; } this.processingInput = true; this.message = 'Processing confirmed voice text…'; this.api.voiceInput(transcript).subscribe({ next: result => { this.voiceReviewTranscript = ''; this.applyResult(result); }, error: () => { this.message = 'Your voice text was not sent. Make sure Laravel is running, then try again.'; this.processingInput = false; } }); }
  discardVoiceTranscript() { this.voiceReviewTranscript = ''; this.voiceTranscript = ''; this.message = 'Voice text discarded.'; }
  private openVoiceReview() { if (!this.voiceTranscript.trim()) { this.message = 'No speech was captured. Check microphone permission, then try again and speak before stopping.'; return; } this.voiceReviewTranscript = this.voiceTranscript; this.message = 'Review and edit the captured voice text, then confirm to parse it.'; }
  async captureReceipt() { if (!Capacitor.isNativePlatform()) { this.message = 'Receipt OCR is available in the Android app. In a browser, paste receipt text below for review.'; return; } this.processingInput = true; try { const photo = await Camera.getPhoto({ quality: 90, resultType: CameraResultType.Uri, source: CameraSource.Camera, saveToGallery: false, correctOrientation: true }); if (!photo.path) throw new Error('No receipt image was captured.'); const result = await TextRecognition.processImage({ path: photo.path }); this.receiptReviewText = result.text.trim(); this.receiptText = this.receiptReviewText; this.message = this.receiptReviewText ? 'Receipt text is ready. Review it before creating item drafts.' : 'No receipt text was found. Enter it manually to continue.'; try { await Filesystem.deleteFile({ path: photo.path }); } catch { /* Camera cache is temporary; the app never persists the image. */ } } catch { this.message = 'Receipt capture or on-device text recognition was cancelled or unavailable.'; } finally { this.processingInput = false; } }
  reviewReceiptText() { const text = this.receiptReviewText.trim() || this.receiptText.trim(); if (!text) { this.message = 'Capture a receipt or enter receipt text before reviewing.'; return; } this.processingInput = true; this.api.receiptTextInput(text).subscribe({ next: result => { this.receiptText = text; this.receiptReviewText = text; this.applyResult(result); }, error: () => { this.processingInput = false; this.message = 'Receipt items could not be validated. Please try again.'; } }); }
  clearReceiptText() { this.receiptText = ''; this.receiptReviewText = ''; this.message = 'Receipt text cleared. No receipt image or text was uploaded.'; }
  useDraft(draft: PantryInputCandidate) { this.applyCandidate(draft, 'Review this draft, then add it to the pantry.'); this.drafts = this.drafts.filter(item => item !== draft); }
  private applyCandidates(candidates: PantryInputCandidate[], message: string) { this.applyResult({ message, candidates, accepted: candidates }); }
  private applyResult(result: { message: string; candidates: PantryInputCandidate[]; accepted?: PantryInputCandidate[]; suggested?: PantryInputCandidate[]; rejected?: PantryInputCandidate[] }) { this.drafts = [...(result.accepted || result.candidates || [])]; this.suggestedCandidates = [...(result.suggested || [])]; this.rejectedCandidates = [...(result.rejected || [])]; const removed = this.rejectedCandidates.map(item => item.message).filter(Boolean).join(' '); this.applyCandidate(this.drafts.shift(), removed ? `${result.message} ${removed}` : result.message); }
  confirmCandidateSuggestion(candidate: PantryInputCandidate) { if (!candidate.suggestion) return; this.applyCandidate({ ...candidate, name: candidate.suggestion.canonical_name, unit: candidate.unit || candidate.suggestion.default_units?.[0] || null }, `Using ${candidate.suggestion.canonical_name}; review before adding.`); this.suggestedCandidates = this.suggestedCandidates.filter(item => item !== candidate); }
  private applyCandidate(candidate: PantryInputCandidate | undefined, message: string) { if (candidate) { this.form.name = candidate.name || this.form.name; this.form.quantity = candidate.quantity || this.form.quantity; this.form.unit = candidate.unit || this.form.unit; this.form.purchase_source = candidate.purchase_source || this.form.purchase_source; this.form.storage_type = candidate.storage_type || this.form.storage_type; } this.message = message; this.processingInput = false; }
  savePantryItem() { if (!this.form.name.trim() || !Number(this.form.quantity) || !this.form.unit.trim()) { this.message = 'Enter an ingredient, a positive quantity, and a unit.'; return; } this.saving = true; this.message = ''; const request = this.editingId ? this.api.updatePantry(this.editingId, this.form) : this.api.addPantry(this.form); request.subscribe({ next: () => { const familyId = this.form.family_id; this.editingId = null; this.form = this.emptyForm(familyId); this.message = 'Pantry item saved.'; this.saving = false; this.loadPantryItems(); }, error: error => { this.message = error?.error?.message || 'Could not save the pantry item.'; this.saving = false; } }); }
  shareWithActiveFamily(item: PantryItem) {
    if (!this.activeFamily) { this.message = 'Choose a family before sharing pantry stock.'; return; }
    if (!confirm(`Move ${item.name} to ${this.activeFamily.name}'s shared pantry? Family meal plans will then count it as available.`)) return;
    this.api.updatePantry(item.id, { family_id: this.activeFamily.id }).subscribe({
      next: () => { this.message = `${item.name} is now available to ${this.activeFamily!.name}'s meal plans.`; this.loadPantryItems(); },
      error: error => this.message = error?.error?.message || `Could not share ${item.name} with the family pantry.`,
    });
  }
  deletePantryItem(item: PantryItem) { if (!confirm(`Delete ${item.name} from the pantry?`)) return; this.api.deletePantry(item.id).subscribe({ next: () => { if (this.editingId === item.id) this.startAdd(); this.message = 'Pantry item deleted.'; this.loadPantryItems(); }, error: () => this.message = 'Could not delete the pantry item.' }); }
  async recordFreshnessAction(item: PantryItem, action: 'still_fresh' | 'spoiled' | 'used' | 'discarded' | 'undo_used') { if (action === 'used') { const modal = await this.modalController.create({ component: UseAmountModalComponent, componentProps: { item }, initialBreakpoint: 0.62, breakpoints: [0, 0.62, 0.9] }); await modal.present(); const { data, role } = await modal.onDidDismiss<{ amount: number; reason: string }>(); if (role !== 'confirm' || !data) return; this.api.updateFreshness(item.id, 'used', data.amount, data.reason).subscribe({ next: ({ item: updated }) => { this.message = `${updated.name} updated.`; this.loadPantryItems(); }, error: error => this.message = error?.error?.message || 'Could not record usage.' }); return; } this.api.updateFreshness(item.id, action).subscribe({ next: ({ item: updated }) => { this.message = `${updated.name} updated.`; this.loadPantryItems(); }, error: error => this.message = error?.error?.message || 'Could not update freshness.' }); }
  isAttention(item: PantryItem): boolean { return item.freshness_status === 'review' || (!!item.freshness_review_date && new Date(item.freshness_review_date).getTime() <= Date.now()); }
  returnToMeal(): void { if (this.returnToMealId) this.router.navigate(['/meal-details', this.returnToMealId]); }
  private readMealReturnContext(): void { const scope = this.route.snapshot.queryParamMap.get('scope'); this.requestedScope = scope === 'family' || scope === 'personal' ? scope : undefined; const familyId = Number(this.route.snapshot.queryParamMap.get('family_id')); this.requestedFamilyId = Number.isInteger(familyId) && familyId > 0 ? familyId : undefined; const mealId = Number(this.route.snapshot.queryParamMap.get('return_to_meal_id')); this.returnToMealId = Number.isInteger(mealId) && mealId > 0 ? mealId : undefined; }
  private emptyForm(familyId: number | null = null): PantryForm { return { name: '', quantity: '1', unit: '', purchase_date: new Date().toISOString().slice(0, 10), expiry_date: '', freshness_review_date: '', purchase_source: 'unknown', storage_type: 'unknown', freshness_condition: 'unknown', family_id: familyId }; }
  private dateOnly(value?: string): string { return value ? value.slice(0, 10) : ''; }
}
